[project]
name = "protocol"
authors = []
description = ""
telemetry = true
requirements = []
analysis = ["check_checker"]
costs_version = 2
[contracts.insurance]
path = "contracts/insurance.clar"
depends_on = []
